variables:
  CURRENT_BRANCH_NAME: sk_content-external-template #"${INFRA_BRANCH}"

include:
  - file: .gitlab/ci/content-external-template/.gitlab-ci.yml
    ref: sk_content-external-template #"${INFRA_BRANCH}"
    project: "${CI_PROJECT_NAMESPACE}/infra"
